spring:
  #redis配置
  redis:
    #redis数据库索引（默认为0）
    database: 0
    #redis服务器地址
    host: 42.193.226.155
    #redis端口
    post: 6379
    #Redis服务器连接密码
    password: leiyuan1008
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间毫秒
    timeout: 5000
  datasource:
    url: jdbc:mysql://42.193.226.155:3306/raffle?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: raffle
    password: raffle1008
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  application:
    name: aRaffle

server:
  port: 8081
